# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
from json.decoder import JSONDecodeError

from PyQt5.QtWidgets import QHBoxLayout

with open('data.json', 'r') as json_file:
    image_info_list = json.load(json_file)
with open('data1.json', 'r') as json_file:
    image_filenames = json.load(json_file)

with open('image_names.json', 'r') as file:
    image_names = json.load(file)
with open('zu_img_info.json', 'r') as json_file:
    zu_img_info = json.load(json_file)
with open('user_data.json', 'r') as json_file:
    user_data = json.load(json_file)
#with open('result.json', 'r') as json_file:
#   war_img_info = json.load(json_file)

try:
    with open('result.json', 'r') as json_file:
        content = json_file.read()

        if not content.strip():
            war_img_info = []
            print("Le fichier est vide.")
        else:
            war_img_info = json.loads(content)
            print("Données chargées :", war_img_info)
            with open('result.json', 'w') as json_file:
                json.dump([], json_file)
except FileNotFoundError:
    war_img_info = []
    print("Le fichier n'existe pas.")
except JSONDecodeError:
    print("Le fichier ne contient pas de JSON valide.")

class klausp(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(917, 623)
        Widget.setMinimumSize(QtCore.QSize(917, 623))
        self.data = user_data["klaus"]
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(Widget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ListButton = QtWidgets.QWidget(self.widget)
        self.ListButton.setMinimumSize(QtCore.QSize(200, 640))
        self.ListButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ListButton.setStyleSheet("QWidget{background-color: rgb(13, 86, 80);}\n"
                                      "QPushButton{background-color:white;}")
        self.ListButton.setObjectName("ListButton")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ListButton)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.ListButton)
        self.widget_3.setStyleSheet("QLabel{\n"
                                    "    color:white;\n"
                                    "}")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setMinimumSize(QtCore.QSize(91, 71))
        self.label.setMaximumSize(QtCore.QSize(200, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/account.png"))
        self.label.setScaledContents(True)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setStyleSheet("font-size:26px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.widget_9 = QtWidgets.QWidget(self.widget_3)
        self.widget_9.setStyleSheet("QLabel{\n"
                                    "    font-size:24px;\n"
                                    "}")
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_2.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_9)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.widget_9)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.widget_9)
        self.verticalLayout_3.setStretch(0, 4)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.ListButton)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(12, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.widget_4)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.ListButton)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")

        self.pushButton_121= QtWidgets.QPushButton(self.widget_5)
        self.pushButton_121.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_121.setText("Log out")
        self.pushButton_121.setStyleSheet("font-size: 24px, color: white")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_121.setIcon(icon1)
        self.pushButton_121.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_121.clicked.connect(self.log_out)

        self.verticalLayout_7.addWidget(self.pushButton_121, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 5)
        self.verticalLayout_2.setStretch(2, 2)
        self.horizontalLayout.addWidget(self.ListButton)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.kauf = QtWidgets.QWidget()
        self.kauf.setObjectName("kauf")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.kauf)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.kauf)
        self.frame.setStyleSheet("QFrame{background-color: rgb(13, 86, 80);}\n"
                                 "\n"
                                 "            QPushButton {\n"
                                 "                background-color: white;\n"
                                 "                color: black;\n"
                                 "                border-radius: 10px;\n"
                                 "                border: 2px solid #2980b9;\n"
                                 "                font-size: 16px;\n"
                                 "            }\n"
                                 "            QPushButton:hover {\n"
                                 "                background-color: #2980b9;\n"
                                 "            }\n"
                                 "            QPushButton:pressed {\n"
                                 "                background-color: #21618c;\n"
                                 "                border: 2px solid #1b4f72;\n"
                                 "            }")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/left-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setStyleSheet("color: white;\n"
                                   "font-size: 28px;\n"
                                   "font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/right-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 6)
        self.horizontalLayout_3.setStretch(2, 2)
        self.verticalLayout.addWidget(self.frame)
        self.widget_6 = QtWidgets.QWidget(self.kauf)
        self.widget_6.setObjectName("widget_6")
        self.widget_6.setStyleSheet("background-color: white;\n"
                                    "border: 1px solid black;"
                                    )

        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_13.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")

        self.verticalLayout.addWidget(self.widget_6)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)
        self.stackedWidget.addWidget(self.kauf)
        self.kaufzu = QtWidgets.QWidget()
        self.kaufzu.setObjectName("kaufzu")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.kaufzu)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_3 = QtWidgets.QFrame(self.kaufzu)
        self.frame_3.setStyleSheet("QFrame{background-color: rgb(13, 86, 80);}\n"

                                   "            QPushButton {\n"
                                   "                background-color: white;\n"
                                   "                color: black;\n"
                                   "                border-radius: 10px;\n"
                                   "                border: 2px solid #2980b9;\n"
                                   "                font-size: 16px;\n"
                                   "            }\n"
                                   "            QPushButton:hover {\n"
                                   "                background-color: #2980b9;\n"
                                   "            }\n"
                                   "            QPushButton:pressed {\n"
                                   "                background-color: #21618c;\n"
                                   "                border: 2px solid #1b4f72;\n"
                                   "            }")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setStyleSheet("color: white;\n"
                                   "font-size: 28px;\n"
                                   "font-weight: bold;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_8.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 6)
        self.horizontalLayout_4.setStretch(2, 2)
        self.verticalLayout_9.addWidget(self.frame_3)
        self.widget_8 = QtWidgets.QWidget(self.kaufzu)
        self.widget_8.setObjectName("widget_8")
        self.widget_8.setStyleSheet("background-color:white;\n")
        #
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_12.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        #
        self.verticalLayout_9.addWidget(self.widget_8)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 9)
        self.stackedWidget.addWidget(self.kaufzu)
        self.warenkorb = QtWidgets.QWidget()
        self.warenkorb.setObjectName("warenkorb")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.warenkorb)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.warenkorb)
        self.frame_2.setStyleSheet("background-color: rgb(13, 86, 80);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setStyleSheet("color: white;\n"
                                   "font-size: 28px;\n"
                                   "font-weight: bold;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.widget_7 = QtWidgets.QWidget(self.warenkorb)
        self.widget_7.setStyleSheet("            QPushButton {\n"
                                    "                background-color: #3498db;\n"
                                    "                color: #ffffff;\n"
                                    "                border-radius: 10px;\n"
                                    "                border: 2px solid #2980b9;\n"
                                    "                font-size: 16px;\n"
                                    "            }\n"
                                    "            QPushButton:hover {\n"
                                    "                background-color: #2980b9;\n"
                                    "            }\n"
                                    "            QPushButton:pressed {\n"
                                    "                background-color: #21618c;\n"
                                    "                border: 2px solid #1b4f72;\n"
                                    "            }")
        self.widget_7.setObjectName("widget_7")

        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_14.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_14.setSpacing(10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")

        self.pushButton_6 = QtWidgets.QPushButton()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/money-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_5.addWidget(self.widget_7)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 9)
        self.stackedWidget.addWidget(self.warenkorb)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_6.addWidget(self.widget)

        self.pushButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))
        self.pushButton_2.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        self.pushButton_3.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))

        self.retranslateUi(Widget)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Widget)

        ###################################### Neue Traktoren ######################################

        self.car_info_list = []

        row_layout_1 = QtWidgets.QHBoxLayout()
        row_layout_1.setObjectName("row_layout_1")
        self.verticalLayout_12.addLayout(row_layout_1)

        row_layout_2 = QtWidgets.QHBoxLayout()
        row_layout_2.setObjectName("row_layout_2")
        self.verticalLayout_12.addLayout(row_layout_2)
        self.int = 0
        self.ind = 0

        for i in range(3):
            frame = QtWidgets.QFrame()
            frame.setStyleSheet("            QPushButton {\n"
                                    "                background-color: #3498db;\n"
                                    "                color: #ffffff;\n"
                                    "                border-radius: 10px;\n"
                                    "                border: 2px solid #2980b9;\n"
                                    "                font-size: 16px;\n"
                                    "            }\n"
                                "QFrame{border: 1px solid grey;}"
                                "QLabel{color: black;}")
            frame.setObjectName(f"frame_1_{i}")
            frame.setLayout(QtWidgets.QVBoxLayout())
            row_layout_1.addWidget(frame)

            frame1 = QtWidgets.QFrame()
            verticalLayout_frame1 = QtWidgets.QVBoxLayout(frame1)
            verticalLayout_frame1.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame1.setSpacing(0)
            verticalLayout_frame1.setObjectName("verticalLayout_frame1")
            frame.layout().addWidget(frame1)

            label_img = QtWidgets.QLabel(frame)
            label_img.setMinimumSize(QtCore.QSize(100, 100))
            label_img.setText("")
            label_img.setScaledContents(True)
            label_img.setObjectName(f"image_label_1_{i}")
            frame1.layout().addWidget(label_img)

            frame2 = QtWidgets.QFrame()
            frame2.setStyleSheet("border: none;")
            verticalLayout_frame2 = QtWidgets.QVBoxLayout(frame2)
            verticalLayout_frame2.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame2.setSpacing(0)
            verticalLayout_frame2.setObjectName("verticalLayout_frame2")
            frame.layout().addWidget(frame2)

            typ_label = QtWidgets.QLabel(frame)
            typ_label.setAlignment(QtCore.Qt.AlignCenter)
            typ_label.setStyleSheet("font-weight: bold;text-decoration: underline")
            typ_label.setObjectName(f"typ_label_1_{i}")
            verticalLayout_frame2.addWidget(typ_label)

            price_label = QtWidgets.QLabel(frame)
            price_label.setAlignment(QtCore.Qt.AlignLeft)
            price_label.setObjectName(f"price_label_1_{i}")
            verticalLayout_frame2.addWidget(price_label)

            hersteller_label = QtWidgets.QLabel(frame)
            hersteller_label.setAlignment(QtCore.Qt.AlignLeft)
            hersteller_label.setObjectName(f"hersteller_label_1_{i}")
            verticalLayout_frame2.addWidget(hersteller_label)

            ps_label = QtWidgets.QLabel(frame)
            ps_label.setAlignment(QtCore.Qt.AlignLeft)
            ps_label.setObjectName(f"ps_label_1_{i}")
            verticalLayout_frame2.addWidget(ps_label)

            km_label = QtWidgets.QLabel(frame)
            km_label.setAlignment(QtCore.Qt.AlignLeft)
            km_label.setObjectName(f"km_label_1_{i}")
            verticalLayout_frame2.addWidget(km_label)

            baujahr_label = QtWidgets.QLabel(frame)
            baujahr_label.setAlignment(QtCore.Qt.AlignLeft)
            baujahr_label.setObjectName(f"baujahr_label_1_{i}")
            verticalLayout_frame2.addWidget(baujahr_label)

            pushButton_12 = QtWidgets.QPushButton(frame)
            pushButton_12.setMinimumSize(QtCore.QSize(90, 30))
            pushButton_12.setText("add zu Warenkorb")
            pushButton_12.setStyleSheet("background-color: green")
            icon1 = QtGui.QIcon()
            icon1.addPixmap(QtGui.QPixmap("images/shopping-cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            pushButton_12.setIcon(icon1)
            pushButton_12.setIconSize(QtCore.QSize(20, 20))
            verticalLayout_frame2.addWidget(pushButton_12)

            pushButton_12.clicked.connect(lambda _, inv=i: self.go_to_warenkorb(inv,True))


            # Ajout d'informations à la liste
            self.car_info_list.append({
                "price_label": price_label,
                "typ_label": typ_label,
                "image_label": label_img,
                "hersteller_label": hersteller_label,
                "ps_label": ps_label,
                "km_label": km_label,
                "baujahr_label": baujahr_label
            })
        inx = 3
        for i in range(3):
            inx += i
            if i == 2:
                inx -= 1
            frame = QtWidgets.QFrame()
            frame.setStyleSheet("            QPushButton {\n"
                                    "                background-color: green;\n"
                                    "                color: #ffffff;\n"
                                    "                border-radius: 10px;\n"
                                    "                border: 2px solid #2980b9;\n"
                                    "                font-size: 16px;\n"
                                    "            }\n"
                                "QFrame{border: 1px solid grey;}"
                                "QLabel{color: black;}")
            frame.setObjectName(f"frame_1_{i}")
            frame.setLayout(QtWidgets.QVBoxLayout())
            row_layout_2.addWidget(frame)

            frame3 = QtWidgets.QFrame()
            frame3.setStyleSheet("border-bottom: 1px solid grey")
            verticalLayout_frame3 = QtWidgets.QVBoxLayout(frame3)
            verticalLayout_frame3.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame3.setSpacing(0)
            verticalLayout_frame3.setObjectName("verticalLayout_frame1")
            frame.layout().addWidget(frame3)

            image_label = QtWidgets.QLabel(frame)
            image_label.setAlignment(QtCore.Qt.AlignLeft)
            image_label.setObjectName(f"image_label_2_{i}")
            image_label.setScaledContents(True)
            verticalLayout_frame3.addWidget(image_label)

            frame4 = QtWidgets.QFrame()
            frame4.setStyleSheet("border: none;")
            verticalLayout_frame4 = QtWidgets.QVBoxLayout(frame4)
            verticalLayout_frame4.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame4.setSpacing(0)
            verticalLayout_frame4.setObjectName("verticalLayout_frame2")
            frame.layout().addWidget(frame4)

            typ_label = QtWidgets.QLabel(frame)
            typ_label.setAlignment(QtCore.Qt.AlignCenter)
            typ_label.setStyleSheet("font-weight: bold;text-decoration: underline")
            typ_label.setObjectName(f"typ_label_2_{i}")
            verticalLayout_frame4.addWidget(typ_label)

            price_label = QtWidgets.QLabel(frame)
            price_label.setAlignment(QtCore.Qt.AlignLeft)
            price_label.setObjectName(f"price_label_2_{i}")
            verticalLayout_frame4.addWidget(price_label)

            hersteller_label = QtWidgets.QLabel(frame)
            hersteller_label.setAlignment(QtCore.Qt.AlignLeft)
            hersteller_label.setObjectName(f"hersteller_label_2_{i}")
            verticalLayout_frame4.addWidget(hersteller_label)

            ps_label = QtWidgets.QLabel(frame)
            ps_label.setAlignment(QtCore.Qt.AlignLeft)
            ps_label.setObjectName(f"ps_label_2_{i}")
            verticalLayout_frame4.addWidget(ps_label)

            km_label = QtWidgets.QLabel(frame)
            km_label.setAlignment(QtCore.Qt.AlignLeft)
            km_label.setObjectName(f"km_label_2_{i}")
            verticalLayout_frame4.addWidget(km_label)

            baujahr_label = QtWidgets.QLabel(frame)
            baujahr_label.setAlignment(QtCore.Qt.AlignLeft)
            baujahr_label.setObjectName(f"baujahr_label_2_{i}")
            verticalLayout_frame4.addWidget(baujahr_label)

            pushButton_12 = QtWidgets.QPushButton(frame)
            pushButton_12.setMinimumSize(QtCore.QSize(90, 30))
            pushButton_12.setText("add zu Warenkorb")
            pushButton_12.setStyleSheet("background-color: green")
            icon1 = QtGui.QIcon()
            icon1.addPixmap(QtGui.QPixmap("images/shopping-cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            pushButton_12.setIcon(icon1)
            pushButton_12.setIconSize(QtCore.QSize(20, 20))
            verticalLayout_frame4.addWidget(pushButton_12)
            pushButton_12.clicked.connect(lambda _, inv=inx: self.go_to_warenkorb(inv,True))

            self.car_info_list.append({
                "price_label": price_label,
                "typ_label": typ_label,
                "image_label": image_label,
                "hersteller_label": hersteller_label,
                "ps_label": ps_label,
                "km_label": km_label,
                "baujahr_label": baujahr_label,
            })
        self.pushButton_8.clicked.connect(self.show_next_images)
        self.pushButton_4.clicked.connect(self.show_previous_imageszu)
        ################################Zubehör######################################################

        self.zu_info_list = []
        self.warenkorb_list = []
        self.new_index = 0
        self.summe_war = 0

        row_layout_3 = QtWidgets.QHBoxLayout()
        row_layout_3.setObjectName("row_layout_3")
        self.verticalLayout_13.addLayout(row_layout_3)

        row_layout_4 = QtWidgets.QHBoxLayout()
        row_layout_4.setObjectName("row_layout_4")
        self.verticalLayout_13.addLayout(row_layout_4)


        for i in range(3):
            frame = QtWidgets.QFrame()
            frame.setStyleSheet("            QPushButton {\n"
                                    "                background-color: green;\n"
                                    "                color: #ffffff;\n"
                                    "                border-radius: 10px;\n"
                                    "                border: 2px solid #2980b9;\n"
                                    "                font-size: 16px;\n"
                                    "            }\n"
                                "QFrame{border: 1px solid grey;}"
                                "QLabel{color: black;}")
            frame.setObjectName(f"frame_1_{i}")
            verticalLayout_frame = QtWidgets.QVBoxLayout(frame)
            verticalLayout_frame.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame.setSpacing(0)
            self.horizontalLayout.setStretch(0, 3)
            verticalLayout_frame.setObjectName("verticalLayout_2")
            row_layout_3.addWidget(frame)

            frame1 = QtWidgets.QFrame()
            frame1.setStyleSheet("border-bottom: 1px solid grey")
            verticalLayout_frame1 = QtWidgets.QVBoxLayout(frame1)
            verticalLayout_frame1.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame1.setSpacing(0)
            verticalLayout_frame1.setObjectName("verticalLayout_frame1")
            frame.layout().addWidget(frame1,3)

            label_img = QtWidgets.QLabel(frame)
            label_img.setMinimumSize(QtCore.QSize(100, 100))
            label_img.setText("")
            label_img.setScaledContents(True)
            label_img.setObjectName(f"image_label_1_{i}")
            frame1.layout().addWidget(label_img)

            frame2 = QtWidgets.QFrame()
            frame2.setStyleSheet("border: none;")
            verticalLayout_frame2 = QtWidgets.QVBoxLayout(frame2)
            verticalLayout_frame2.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame2.setSpacing(0)
            verticalLayout_frame2.setObjectName("verticalLayout_frame2")
            frame.layout().addWidget(frame2,2)

            typ_label = QtWidgets.QLabel(frame)
            typ_label.setAlignment(QtCore.Qt.AlignCenter)
            typ_label.setStyleSheet("font-weight: bold;text-decoration: underline")
            typ_label.setObjectName(f"typ_label_1_{i}")
            frame2.layout().addWidget(typ_label)

            kompat_label = QtWidgets.QLabel(frame)
            kompat_label.setAlignment(QtCore.Qt.AlignLeft)
            kompat_label.setObjectName(f"kompat_label_1_{i}")
            frame2.layout().addWidget(kompat_label)

            price_label = QtWidgets.QLabel(frame)
            price_label.setAlignment(QtCore.Qt.AlignLeft)
            price_label.setObjectName(f"price_label_1_{i}")
            frame2.layout().addWidget(price_label)

            pushButton_12 = QtWidgets.QPushButton(frame)
            pushButton_12.setMinimumSize(QtCore.QSize(90, 30))
            pushButton_12.setText("add zu Warenkorb")
            pushButton_12.setStyleSheet("background-color: green")
            icon1 = QtGui.QIcon()
            icon1.addPixmap(QtGui.QPixmap("images/shopping-cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            pushButton_12.setIcon(icon1)
            pushButton_12.setIconSize(QtCore.QSize(20, 20))
            verticalLayout_frame2.addWidget(pushButton_12)
            pushButton_12.clicked.connect(lambda _, inv=i: self.go_to_warenkorb(inv,False))

            # Ajout d'informations à la liste
            self.zu_info_list.append({
                "price_label": price_label,
                "kompat_label": kompat_label,
                "image_label": label_img,
                "typ_label": typ_label,
            })
        inx=3
        for i in range(3):
            inx += i
            if i == 2:
                inx -= 1
            frame = QtWidgets.QFrame()
            frame.setStyleSheet("            QPushButton {\n"
                                    "                background-color: green;\n"
                                    "                color: #ffffff;\n"
                                    "                border-radius: 10px;\n"
                                    "                border: 2px solid #2980b9;\n"
                                    "                font-size: 16px;\n"
                                    "            }\n"
                                "QFrame{border: 1px solid grey;}"
                                "QLabel{color: black;}")
            frame.setObjectName(f"frame_1_{i}")
            verticalLayout_frame = QtWidgets.QVBoxLayout(frame)
            verticalLayout_frame.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame.setSpacing(0)
            self.horizontalLayout.setStretch(0, 3)
            verticalLayout_frame.setObjectName("verticalLayout_3")
            row_layout_4.addWidget(frame)

            frame3 = QtWidgets.QFrame()
            frame3.setStyleSheet("border-bottom: 1px solid grey")
            verticalLayout_frame3 = QtWidgets.QVBoxLayout(frame3)
            verticalLayout_frame3.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame3.setSpacing(0)
            verticalLayout_frame3.setObjectName("verticalLayout_frame1")
            frame.layout().addWidget(frame3,3)

            label_img = QtWidgets.QLabel(frame)
            label_img.setMinimumSize(QtCore.QSize(100, 100))
            label_img.setText("")
            label_img.setScaledContents(True)
            label_img.setObjectName(f"image_label_1_{i}")
            frame3.layout().addWidget(label_img)

            frame4 = QtWidgets.QFrame()
            frame4.setStyleSheet("border: none;")
            verticalLayout_frame4 = QtWidgets.QVBoxLayout(frame4)
            verticalLayout_frame4.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame4.setSpacing(0)
            verticalLayout_frame4.setObjectName("verticalLayout_frame2")
            frame.layout().addWidget(frame4,2)

            typ_label = QtWidgets.QLabel(frame)
            typ_label.setAlignment(QtCore.Qt.AlignCenter)
            typ_label.setStyleSheet("font-weight: bold;text-decoration: underline")
            typ_label.setObjectName(f"typ_label_2_{i}")
            frame4.layout().addWidget(typ_label)

            kompat_label = QtWidgets.QLabel(frame)
            kompat_label.setAlignment(QtCore.Qt.AlignLeft)
            kompat_label.setObjectName(f"kompat_label_2_{i}")
            frame4.layout().addWidget(kompat_label)

            price_label = QtWidgets.QLabel(frame)
            price_label.setAlignment(QtCore.Qt.AlignLeft)
            price_label.setObjectName(f"price_label_2_{i}")
            frame4.layout().addWidget(price_label)

            pushButton_12 = QtWidgets.QPushButton(frame)
            pushButton_12.setMinimumSize(QtCore.QSize(90, 30))
            pushButton_12.setText("add zu Warenkorb")
            pushButton_12.setStyleSheet("background-color: green")
            icon1 = QtGui.QIcon()
            icon1.addPixmap(QtGui.QPixmap("images/shopping-cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            pushButton_12.setIcon(icon1)
            pushButton_12.setIconSize(QtCore.QSize(20, 20))
            verticalLayout_frame4.addWidget(pushButton_12)
            pushButton_12.clicked.connect(lambda _, inv=inx: self.go_to_warenkorb(inv,False))

            self.zu_info_list.append({
                "price_label": price_label,
                "kompat_label": kompat_label,
                "image_label": label_img,
                "typ_label": typ_label,
            })

    ###########################Warenkorb####################################

        frame51 = QtWidgets.QFrame()
        frame51.setStyleSheet("border-bottom: 1px solid black, background-color: red")
        verticalLayout_frame51 = QtWidgets.QVBoxLayout(frame51)
        verticalLayout_frame51.setContentsMargins(0, 0, 0, 0)
        verticalLayout_frame51.setSpacing(0)
        verticalLayout_frame51.setObjectName("verticalLayout_frame1")
        #self.verticalLayout_14.addLayout(frame51,4)
        self.verticalLayout_14.addWidget(frame51,6)

        frame61 = QtWidgets.QFrame()
        verticalLayout_frame61 = QtWidgets.QVBoxLayout(frame61)
        verticalLayout_frame61.setContentsMargins(0, 0, 0, 0)
        verticalLayout_frame61.setSpacing(0)
        verticalLayout_frame61.setObjectName("verticalLayout_frame1")
        self.verticalLayout_14.addWidget(frame61,1)

        self.framewar = QtWidgets.QFrame()
        self.framewar.setStyleSheet("QFrame{border: 1px solid grey;}"
                            "QLabel{color: black;}")
        self.framewar.setObjectName(f"frame_1_{i}")
        self.verticalLayout_framewar = QtWidgets.QVBoxLayout(self.framewar)
        self.verticalLayout_framewar.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_framewar.setSpacing(0)
        self.verticalLayout_framewar.setObjectName("verticalLayout_framwar")
        verticalLayout_frame51.addWidget(self.framewar)
        self.msg = QtWidgets.QLabel(self.framewar)
        self.msg.setAlignment(QtCore.Qt.AlignCenter)
        self.msg.setStyleSheet("font-weight: bold; border: none; font-size: 25px")
        self.msg.setText("Warenkorb leer...")
        self.verticalLayout_framewar.addWidget(self.msg)
        frame = QtWidgets.QFrame()
        frame.setStyleSheet("QFrame{border: 1px solid grey;}"
                            "QLabel{color: black;}")
        frame.setObjectName(f"frame_1_{i}")
        verticalLayout_frame = QHBoxLayout(frame)
        verticalLayout_frame.setContentsMargins(0, 0, 0, 0)
        verticalLayout_frame.setSpacing(0)
        self.horizontalLayout.setStretch(0, 3)
        verticalLayout_frame.setObjectName("verticalLayout_3")
        verticalLayout_frame61.addWidget(frame)

        gesampt = QtWidgets.QLabel(frame)
        gesampt.setAlignment(QtCore.Qt.AlignCenter)
        gesampt.setStyleSheet("font-weight: bold;text-decoration: underline; border: none; font-size: 25px")
        gesampt.setText("Gesamte Preis: ")
        verticalLayout_frame.addWidget(gesampt,2)
        self.gesamptp = QtWidgets.QLabel(frame)
        self.gesamptp.setAlignment(QtCore.Qt.AlignVCenter)
        self.gesamptp.setStyleSheet("font-weight: bold;font-size: 28px; border: none")
        self.gesamptp.setText("0 €")
        verticalLayout_frame.addWidget(self.gesamptp, 2)
        verticalLayout_frame.addWidget(self.pushButton_6,1)


        self.current_image_index = 0
        self.war_index = 0

        self.show_images(self.current_image_index)
        self.show_imageszu(self.new_index)
        self.pushButton_7.clicked.connect(self.show_previous_images)
        self.pushButton_5.clicked.connect(self.show_next_imageszu)

    ###################################### Neue Traktoren Funktion######################################
    def show_images(self, start_index):
        for i in range(6):
            car_info = self.car_info_list[i]
            car_info["image_label"].clear()

        for i in range(6):
            index = start_index + i

            if index <= len(image_info_list):
                image_info = image_info_list[index]

            if index <= len(image_filenames):
                pixmap = QtGui.QPixmap(image_filenames[index])
                pixmap = pixmap.scaledToWidth(300)

                car_info = self.car_info_list[i]
                car_info["image_label"].setPixmap(pixmap)

                image_info = image_info_list[index]

                car_info["typ_label"].setText(image_info["typ"])
                car_info["price_label"].setText(image_info["price"])
                car_info["hersteller_label"].setText(image_info["hersteller"])
                car_info["ps_label"].setText(image_info["ps"])
                car_info["km_label"].setText(image_info["km"])
                car_info["baujahr_label"].setText(image_info["baujahr"])

    def show_previous_images(self):

        if self.current_image_index > 0:
            self.current_image_index -= 6
            self.ind -= 6
            self.show_images(self.current_image_index)

    def show_next_images(self):
        if self.current_image_index + 6 < len(image_filenames):
            print("Current index before:", self.current_image_index)
            self.current_image_index += 6
            self.ind += 6
            print("Current index after:", self.current_image_index)
            self.show_images(self.current_image_index)

    ################################Zubehör fonktion ######################################################

    def show_imageszu(self, start_indexzu):

        for i in range(6):
            zu_info = self.zu_info_list[i]
            zu_info["image_label"].clear()

        for i in range(6):
            print(f"the start_indexzu ist ${start_indexzu}")
            index = start_indexzu + i
            print(f"the index ist ${index}")

            if index <= len(zu_img_info):
                image_info = zu_img_info[index]

                if index <= len(image_names):
                    pixmap = QtGui.QPixmap(image_names[index])
                    pixmap = pixmap.scaledToWidth(300)

                    zu_info = self.zu_info_list[i]
                    zu_info["image_label"].setPixmap(pixmap)

                    zu_info["typ_label"].setText(image_info["typ"])
                    zu_info["price_label"].setText(image_info["price"])
                    zu_info["kompat_label"].setText(image_info["kompat"])

    def show_previous_imageszu(self):

        if self.new_index > 0:
            self.new_index -= 6
            self.int -= 6
            self.show_imageszu(self.new_index)

    def show_next_imageszu(self):
        if self.new_index + 6 < len(image_names):
            print("New index before:", self.new_index)
            self.new_index += 6
            self.int += 6

            print("New index after:", self.new_index)
            self.show_imageszu(self.new_index)

    ##############go ot Warenkorb####################
    def go_to_warenkorb(self,inv,test):

        try:
            with open('result.json', 'r') as json_file:
                content = json_file.read()

                if not content.strip():
                    result_list = []
                else:
                    result_list = json.loads(content)
        except FileNotFoundError:
            result_list = []

        if len(result_list) < 3:
            if test == True:
                help = inv + self.ind
                info = image_info_list[help]
                if info["menge"] == 0:
                    self.show_menge_warning()
                    return 1
                else:
                    result_list.append({
                        "image": image_filenames[help],
                        "price": info["price"],
                        "name": info["typ"],
                        "hersteller": info["hersteller"],
                        "index": help,
                        "bool": "true"
                    })
            if test == False:
                help = inv + self.int
                info = zu_img_info[help]
                result_list.append({
                    "image": image_names[help],
                    "price": info["price"],
                    "name": info["typ"],
                    "index": help,
                    "bool": "false"
                })

        with open('result.json', 'w') as json_file:
            json.dump(result_list, json_file)
        if len(result_list) == 1:
            for i in range(self.framewar.layout().count()):
                widget = self.framewar.layout().itemAt(i).widget()
                if widget is not None:
                    widget.deleteLater()

            self.frameh = QtWidgets.QFrame()
            self.frameh.setObjectName(f"frame_1_1")
            self.frameh.setMaximumHeight(250)
            horizontalLayout_frame = QtWidgets.QHBoxLayout()
            self.frameh.setLayout(horizontalLayout_frame)
            horizontalLayout_frame.setContentsMargins(2, 2, 2, 2)
            horizontalLayout_frame.setSpacing(10)
            horizontalLayout_frame.setObjectName("verticalLayout_3")
            self.verticalLayout_framewar.addWidget( self.frameh,1)

            frame1 = QtWidgets.QFrame()
            verticalLayout_frame1 = QtWidgets.QVBoxLayout(frame1)
            verticalLayout_frame1.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame1.setSpacing(0)
            verticalLayout_frame1.setObjectName("verticalLayout_frame1")
            self.frameh.layout().addWidget(frame1)

            label_img = QtWidgets.QLabel( self.frameh)
            label_img.setMinimumSize(QtCore.QSize(100, 100))
            label_img.setText("")
            label_img.setScaledContents(True)
            label_img.setObjectName(f"image_label_1_1")
            frame1.layout().addWidget(label_img)

            print("nouvelle page")
            frame2 = QtWidgets.QFrame()
            frame2.setStyleSheet("border: none;")
            verticalLayout_frame2 = QtWidgets.QVBoxLayout(frame2)
            verticalLayout_frame2.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame2.setSpacing(0)
            verticalLayout_frame2.setObjectName("verticalLayout_frame2")
            self.frameh.layout().addWidget(frame2)

            typ_label = QtWidgets.QLabel( self.frameh)
            typ_label.setAlignment(QtCore.Qt.AlignCenter)
            typ_label.setStyleSheet("font-weight: bold;text-decoration: underline")
            typ_label.setObjectName(f"typ_label_1_1")
            verticalLayout_frame2.addWidget(typ_label)

            price_label = QtWidgets.QLabel( self.frameh)
            price_label.setAlignment(QtCore.Qt.AlignLeft)
            price_label.setObjectName(f"price_label_1_1")
            verticalLayout_frame2.addWidget(price_label)


            remove_btn = QtWidgets.QPushButton( self.frameh)

            self.warenkorb_list.append({
                "price_label": price_label,
                "typ_label": typ_label,
                "image_label": label_img,
            })
        if len(result_list) == 2:
            frame = QtWidgets.QFrame()
            frame.setObjectName(f"frame_1_2")
            horizontalLayout_frame = QtWidgets.QHBoxLayout()
            frame.setLayout(horizontalLayout_frame)
            horizontalLayout_frame.setContentsMargins(2, 2, 2, 2)
            horizontalLayout_frame.setSpacing(10)
            horizontalLayout_frame.setObjectName("verticalLayout_3")
            self.verticalLayout_framewar.addWidget(frame, 1)

            frame1 = QtWidgets.QFrame()
            verticalLayout_frame1 = QtWidgets.QVBoxLayout(frame1)
            verticalLayout_frame1.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame1.setSpacing(0)
            verticalLayout_frame1.setObjectName("verticalLayout_frame1")
            frame.layout().addWidget(frame1)

            label_img = QtWidgets.QLabel(frame)
            label_img.setMinimumSize(QtCore.QSize(100, 100))
            label_img.setText("")
            label_img.setScaledContents(True)
            label_img.setObjectName(f"image_label_1_2")
            frame1.layout().addWidget(label_img)

            frame2 = QtWidgets.QFrame()
            frame2.setStyleSheet("border: none;")
            verticalLayout_frame2 = QtWidgets.QVBoxLayout(frame2)
            verticalLayout_frame2.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame2.setSpacing(0)
            verticalLayout_frame2.setObjectName("verticalLayout_frame2")
            frame.layout().addWidget(frame2)

            typ_label = QtWidgets.QLabel(frame)
            typ_label.setAlignment(QtCore.Qt.AlignCenter)
            typ_label.setStyleSheet("font-weight: bold;text-decoration: underline")
            typ_label.setObjectName(f"typ_label_1_2")
            verticalLayout_frame2.addWidget(typ_label)

            price_label = QtWidgets.QLabel(frame)
            price_label.setAlignment(QtCore.Qt.AlignLeft)
            price_label.setObjectName(f"price_label_1_2")
            verticalLayout_frame2.addWidget(price_label)

            self.warenkorb_list.append({
                "price_label": price_label,
                "typ_label": typ_label,
                "image_label": label_img,
            })
        if len(result_list) == 3:
            frame = QtWidgets.QFrame()
            frame.setObjectName(f"frame_1_3")
            horizontalLayout_frame = QtWidgets.QHBoxLayout()
            frame.setLayout(horizontalLayout_frame)
            horizontalLayout_frame.setContentsMargins(2, 2, 2, 2)
            horizontalLayout_frame.setSpacing(10)
            horizontalLayout_frame.setObjectName("verticalLayout_3")
            self.verticalLayout_framewar.addWidget(frame, 1)

            frame1 = QtWidgets.QFrame()
            verticalLayout_frame1 = QtWidgets.QVBoxLayout(frame1)
            verticalLayout_frame1.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame1.setSpacing(0)
            verticalLayout_frame1.setObjectName("verticalLayout_frame1")
            frame.layout().addWidget(frame1)

            label_img = QtWidgets.QLabel(frame)
            label_img.setMinimumSize(QtCore.QSize(100, 100))
            label_img.setText("")
            label_img.setScaledContents(True)
            label_img.setObjectName(f"image_label_1_3")
            frame1.layout().addWidget(label_img)

            frame2 = QtWidgets.QFrame()
            frame2.setStyleSheet("border: none;")
            verticalLayout_frame2 = QtWidgets.QVBoxLayout(frame2)
            verticalLayout_frame2.setContentsMargins(0, 0, 0, 0)
            verticalLayout_frame2.setSpacing(0)
            verticalLayout_frame2.setObjectName("verticalLayout_frame2")
            frame.layout().addWidget(frame2)

            typ_label = QtWidgets.QLabel(frame)
            typ_label.setAlignment(QtCore.Qt.AlignCenter)
            typ_label.setStyleSheet("font-weight: bold;text-decoration: underline")
            typ_label.setObjectName(f"typ_label_1_3")
            verticalLayout_frame2.addWidget(typ_label)

            price_label = QtWidgets.QLabel(frame)
            price_label.setAlignment(QtCore.Qt.AlignLeft)
            price_label.setObjectName(f"price_label_1_3")
            verticalLayout_frame2.addWidget(price_label)

            self.warenkorb_list.append({
                "price_label": price_label,
                "typ_label": typ_label,
                "image_label": label_img,
            })


        for i in range(3):
            if i == 3 :
                break
            index = self.war_index + i
            if index < len(self.warenkorb_list):
                war_info = self.warenkorb_list[index]

            if index < len(result_list):
                war_img = result_list[index]
                pixmap = QtGui.QPixmap(war_img["image"])
                pixmap = pixmap.scaledToWidth(300)

                prix_string = war_img["price"]
                prix_nombre = float(prix_string.replace('\u20ac', '').replace(',', '.'))

                self.summe_war += prix_nombre
                self.gesamptp.setText(f"{self.summe_war} €")

                war_info["image_label"].setPixmap(pixmap)
                war_info["typ_label"].setText(war_img["name"])
                war_info["price_label"].setText("Preis : " + war_img["price"])
        self.pushButton_6.clicked.connect(lambda: self.bezahlen(result_list))
        self.pushButton_6.clicked.connect(lambda: result_list.clear())
    def bezahlen(self,result_list):
        budget = self.data["budget"]
        if budget < self.summe_war:
            print("budget insuffisant")
            self.show_budget_warning()
        else:
            budget = budget - self.summe_war

            self.data["budget"] = budget
            user_data["klaus"] = self.data
            with open('user_data.json', 'w') as json_file:
                json.dump(user_data, json_file, indent=2)
            self.label_3.setText(str(self.data["budget"]))
            self.gesamptp.setText("0 €")
            for i in range(len(result_list)):
                element = result_list[i]
                index = element["index"]

            result_list = []
            with open('result.json', 'w') as json_file:
                json.dump(result_list, json_file)
            print("payé!!!")
            for i in range(self.framewar.layout().count()):
                widget = self.framewar.layout().itemAt(i).widget()
                if widget is not None:
                    widget.deleteLater()
    def log_out(self):
        self.widget.parent().close()

    def show_budget_warning(self):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Warning)
        msg.setText("Ihre Budget ist nicht genug")
        msg.setWindowTitle("Warning")
        msg.exec_()

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Traktor_Shop"))
        self.label_2.setText(_translate("Widget", self.data["name"]))
        self.label_3.setText(_translate("Widget", str(self.data["budget"])))
        self.label_6.setText(_translate("Widget", "€"))
        self.pushButton_2.setText(_translate("Widget", "Traktoren"))
        self.pushButton.setText(_translate("Widget", "Zubehörde"))
        self.pushButton_3.setText(_translate("Widget", "Warenkorb"))
        self.pushButton_4.setText(_translate("Widget", "Prev"))
        self.label_4.setText(_translate("Widget", "Zubehörde"))
        self.pushButton_5.setText(_translate("Widget", "Next"))
        self.pushButton_7.setText(_translate("Widget", "Prev"))
        self.label_8.setText(_translate("Widget", "Neue Traktoren"))
        self.pushButton_8.setText(_translate("Widget", "Next"))
        self.label_7.setText(_translate("Widget", "Warenkorb"))
        self.pushButton_6.setText(_translate("Widget", "Bezahlen"))


if __name__ == "__main__":
    import sys


    class MyApplication(QtWidgets.QWidget):
        def __init__(self):
            super().__init__()

            self.ui = klausp()
            self.ui.setupUi(self)


    app = QtWidgets.QApplication(sys.argv)
    window = MyApplication()
    window.show()
    sys.exit(app.exec_())
